# From https://www.freecodecamp.org/news/how-to-deploy-next-js-app-to-github-pages/

name: setup-node
description: "Sets up NodeJS"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache Dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
